variables:
  DART_SASS_VERSION: 1.69.5
  HUGO_VERSION: 0.121.0
  NODE_VERSION: 20.x
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  TZ: America/Los_Angeles

image:
  name: golang:1.20.6-bookworm

pages:
  stage: deploy
  script:
   - mkdir .public
   - cp -r docs/* .public
   - mv .public public   
  artifacts:
    paths:
      - public
  only: 
     - main  
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


