baseURL = "https://rachnasrivastava.com/"
title = "Hello from Rachna"
copyright = "Copyright © 2022"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
theme = "calligraphy"
enableInlineShortcodes = true
enableEmoji = true

[params]
  tagline = "Elegant Writing"
  cdn = false

[params.meta]
  baseOGImage = "img/screenshot.jpg"
  faviconComplete = true
  faviconSVG = true
  faviconVersion = ""
  faviconMSColor = "#00aba9"
  faviconiOSColor = "#00aba9"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "books"
  name = "Books"
  url = "/books/"
  weight = 30

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 40

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 45

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 50

################################################################################
######       The block below has additional configuration settings.        #####
######         Users can edit, but for most it won't be necessary.         #####
################################################################################

[taxonomies]
  author = "authors"
  series = "series"
  category = "categories"
  tag = "tags"
  books = "books"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[module.hugoVersion]
  extended = true
  min = "0.89.0"

[privacy.twitter]
  enableDNT = true

[privacy.vimeo]
  enableDNT = true

[privacy.youtube]
  privacyEnhanced = true
